apiVersion: v1
kind: PersistentVolume
metadata:
  name: intranet-spring-db-pv
  labels:
    type: local
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/mysql"
    type: Directory